"""Initial migration

Revision ID: 9a748b92602a
Revises: 
Create Date: 2025-02-05 23:45:20.473743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a748b92602a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ocurrence')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index('ix_courses_coursename')

    op.drop_table('courses')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index('ix_students_username')

    op.drop_table('students')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username')

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('semester')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', sa.VARCHAR(length=64), nullable=True))

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_username', ['username'], unique=1)

    op.create_table('students',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index('ix_students_username', ['username'], unique=1)

    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('coursename', sa.VARCHAR(length=64), nullable=True),
    sa.Column('coursedescription', sa.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index('ix_courses_coursename', ['coursename'], unique=1)

    op.create_table('ocurrence',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ocurrencediscipline', sa.VARCHAR(length=64), nullable=True),
    sa.Column('ocurrencedatetime', sa.DATETIME(), nullable=True),
    sa.Column('ocurrencedescription', sa.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('occurrences')
    # ### end Alembic commands ###
